import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {  MatToolbarModule,
          MatSidenavModule,
          MatButtonModule,
          MatMenuModule,
          MatIconModule,
          MatListModule,
          MatSelectModule,
          MatInputModule,
          MatAutocompleteModule,
          MatFormFieldModule,
          MatDialogModule,
          MatTabsModule,
          MatSliderModule,
          MatCardModule,
          MatTableModule,
          MatSortModule,
          MatPaginatorModule,
          MatTooltipModule,
          MatProgressBarModule,
          MatNativeDateModule,
          MatRadioModule,
          MatChipsModule,
          MatCheckboxModule,
          MatProgressSpinnerModule,
          MatButtonToggleModule,
          MatSlideToggleModule,
          MatSnackBarModule,
          MatGridListModule,
          MatBadgeModule,
          MatStepperModule
        } from '@angular/material';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatExpansionModule } from '@angular/material/expansion';
import {MatRippleModule} from '@angular/material/core';

@NgModule({
  imports: [
    CommonModule,
    MatToolbarModule,
    MatSidenavModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,
    MatInputModule,
    MatAutocompleteModule,
    MatFormFieldModule,
    MatDialogModule,
    MatTabsModule,
    MatSliderModule,
    MatCardModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatNativeDateModule,
    MatRadioModule,
    MatChipsModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatGridListModule,
    MatBadgeModule,
    MatRippleModule,
    MatStepperModule
  ],
  exports: [
    MatToolbarModule,
    MatSidenavModule,
    MatButtonModule,
    MatMenuModule,
    MatIconModule,
    MatListModule,
    MatSelectModule,
    MatInputModule,
    MatAutocompleteModule,
    MatFormFieldModule,
    MatDialogModule,
    MatTabsModule,
    MatSliderModule,
    MatCardModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatTooltipModule,
    MatProgressBarModule,
    MatDatepickerModule,
    MatExpansionModule,
    MatNativeDateModule,
    MatRadioModule,
    MatChipsModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatButtonToggleModule,
    MatSlideToggleModule,
    MatSnackBarModule,
    MatGridListModule,
    MatBadgeModule,
    MatRippleModule,
    MatStepperModule
  ],
  declarations: []
})
export class MaterialModule { }
